const catchError = require("./catchError");
const catchAsyncError = require("./catchAsyncError");

module.exports = { catchError, catchAsyncError };
